# 应用名称
spring:
  application:
    name: health
  author: yanmingkui
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health?serverTimezone=GMT%2b8
    username: root
    password: Yo*tja>AF96;

  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    # redis服务器地址（默认为loaclhost）
    #  host: 192.168.73.12
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    #    password: pwd123
    # redis连接超时时间（单位毫秒）
    timeout: 1000
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

  #配置邮件
  mail:
    # smtp 主机
    host: smtp.163.com
    # 服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    # 允许测试链接
    test-connection: true
    # 设置发件人
    username: 13905142704@163.com
    # 授权码
    password: QOCFBNOIBCASAHJT


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ymk.health.entity
  configuration:
    # 打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰
    map-underscore-to-camel-case: true

# 应用服务 WEB 访问端口
server:
  port: 9090
# jwt 配置
jwt:
  # 请求头
  tokenHeader: Authorization
  # 签名密码
  secret: ymkztt9897
  # 过期时间(s)
  expiration: 18000
  # token 头部
  tokenHead: 'Bearer '

# 七牛云
qiniu:
  accessKey: 4Sd_qnJn_Q80bBrHs2DqZjLMdWY9TzSPAFXxReV1
  secretKey: HW_yjT1cwWGNW6acmW7QOfgsGGjcOzxy6bMPHgyp
  bucket: ymk-health
